//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZXLightspeedGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZXLightspeedGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AboutOKButton {
            get {
                return ResourceManager.GetString("AboutOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About EZX Account Risk GUI.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettingsWindowTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EZX Account Risk Settings Manager  - {0}.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply these settings for all UI sessions ?.
        /// </summary>
        public static string ApplySettingsForAllSessionsCheckBoxText {
            get {
                return ResourceManager.GetString("ApplySettingsForAllSessionsCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2014 EZX inc..
        /// </summary>
        public static string CopyrightText1 {
            get {
                return ResourceManager.GetString("CopyrightText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string CopyrightText2 {
            get {
                return ResourceManager.GetString("CopyrightText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTabTitle {
            get {
                return ResourceManager.GetString("GeneralTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string hgh {
            get {
                return ResourceManager.GetString("hgh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string hghf {
            get {
                return ResourceManager.GetString("hghf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportDataWindowTitle {
            get {
                return ResourceManager.GetString("ImportDataWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        public static string ImportErrorWindowTitle {
            get {
                return ResourceManager.GetString("ImportErrorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string jhr {
            get {
                return ResourceManager.GetString("jhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string LogEnableHeader {
            get {
                return ResourceManager.GetString("LogEnableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is required!.
        /// </summary>
        public static string LoginCompanyError {
            get {
                return ResourceManager.GetString("LoginCompanyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string LoginCompanyLabel {
            get {
                return ResourceManager.GetString("LoginCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Completed at {0}.
        /// </summary>
        public static string LoginCompletedText {
            get {
                return ResourceManager.GetString("LoginCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} at {2}.
        /// </summary>
        public static string LoginConnectText {
            get {
                return ResourceManager.GetString("LoginConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} at {2}.
        /// </summary>
        public static string LoginDisconnectText {
            get {
                return ResourceManager.GetString("LoginDisconnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit login details.
        /// </summary>
        public static string LoginEditBoxTitle {
            get {
                return ResourceManager.GetString("LoginEditBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Connect (Host: {0} , Port:{1}, Company:{2}, Use SSL: {3}, at {4}).
        /// </summary>
        public static string LoginFailedToConnectText {
            get {
                return ResourceManager.GetString("LoginFailedToConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is required!.
        /// </summary>
        public static string LoginHostError {
            get {
                return ResourceManager.GetString("LoginHostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string LoginHostLabel {
            get {
                return ResourceManager.GetString("LoginHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string LoginPortLabel {
            get {
                return ResourceManager.GetString("LoginPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for Port!.
        /// </summary>
        public static string LoginPortValueError {
            get {
                return ResourceManager.GetString("LoginPortValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginSettingCancelButtonLabel {
            get {
                return ResourceManager.GetString("LoginSettingCancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LoginSettingEditButtonLabel {
            get {
                return ResourceManager.GetString("LoginSettingEditButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login settings.
        /// </summary>
        public static string LoginSettingTabTitle {
            get {
                return ResourceManager.GetString("LoginSettingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string LoginUseSSLLabel {
            get {
                return ResourceManager.GetString("LoginUseSSLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LogLevelHeader {
            get {
                return ResourceManager.GetString("LogLevelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LogNameHeader {
            get {
                return ResourceManager.GetString("LogNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log settings.
        /// </summary>
        public static string LogSettingHeader {
            get {
                return ResourceManager.GetString("LogSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string SettingApplyButtonLabel {
            get {
                return ResourceManager.GetString("SettingApplyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingCancelButtonLabel {
            get {
                return ResourceManager.GetString("SettingCancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SettingOKButtonLabel {
            get {
                return ResourceManager.GetString("SettingOKButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Executed ($):.
        /// </summary>
        public static string ST_AggregateExecuted {
            get {
                return ResourceManager.GetString("ST_AggregateExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit ($):.
        /// </summary>
        public static string ST_CreditLimit {
            get {
                return ResourceManager.GetString("ST_CreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sell Short:.
        /// </summary>
        public static string ST_EnableSellShort {
            get {
                return ResourceManager.GetString("ST_EnableSellShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sell Short Exempt:.
        /// </summary>
        public static string ST_EnableSellShortExempt {
            get {
                return ResourceManager.GetString("ST_EnableSellShortExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equities Wash Check:.
        /// </summary>
        public static string ST_EQUITYWASHCHECK {
            get {
                return ResourceManager.GetString("ST_EQUITYWASHCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. $/Order (Options):.
        /// </summary>
        public static string ST_MaxAmountPerOptionOrder {
            get {
                return ResourceManager.GetString("ST_MaxAmountPerOptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. $/Order (Equity):.
        /// </summary>
        public static string ST_MaxAmountPerOrder {
            get {
                return ResourceManager.GetString("ST_MaxAmountPerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Duplicate Orders:.
        /// </summary>
        public static string ST_MaxDuplicateOrder {
            get {
                return ResourceManager.GetString("ST_MaxDuplicateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Order Interval (ms):.
        /// </summary>
        public static string ST_MaxDuplicateOrderInterval {
            get {
                return ResourceManager.GetString("ST_MaxDuplicateOrderInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Net Traded ($):.
        /// </summary>
        public static string ST_MaxNetTraded {
            get {
                return ResourceManager.GetString("ST_MaxNetTraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Open Orders:.
        /// </summary>
        public static string ST_MaxOpenOrders {
            get {
                return ResourceManager.GetString("ST_MaxOpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Order Size:.
        /// </summary>
        public static string ST_MaxOrderSize {
            get {
                return ResourceManager.GetString("ST_MaxOrderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Erroneous Price (%):.
        /// </summary>
        public static string ST_MaxPriceDiff {
            get {
                return ResourceManager.GetString("ST_MaxPriceDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Shares/Order (Options):.
        /// </summary>
        public static string ST_MaxSharesPerOptionOrder {
            get {
                return ResourceManager.GetString("ST_MaxSharesPerOptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Shares/Order (Equity):.
        /// </summary>
        public static string ST_MaxSharesPerOrder {
            get {
                return ResourceManager.GetString("ST_MaxSharesPerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC/LOC Allowed:.
        /// </summary>
        public static string ST_MOCLOCAllowed {
            get {
                return ResourceManager.GetString("ST_MOCLOCAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC/LOC Cut-off Time:.
        /// </summary>
        public static string ST_MOCLOCAllowedLatestTime {
            get {
                return ResourceManager.GetString("ST_MOCLOCAllowedLatestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Wash Check:.
        /// </summary>
        public static string ST_OPTIONWASHCHECK {
            get {
                return ResourceManager.GetString("ST_OPTIONWASHCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not found).
        /// </summary>
        public static string ST_SettingNotFoundFromServer {
            get {
                return ResourceManager.GetString("ST_SettingNotFoundFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syslog Host.
        /// </summary>
        public static string SyslogHostLable {
            get {
                return ResourceManager.GetString("SyslogHostLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built on {0}.
        /// </summary>
        public static string VersionDateText {
            get {
                return ResourceManager.GetString("VersionDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EZX Account Risk GUI - {0}.
        /// </summary>
        public static string VersionNumberText {
            get {
                return ResourceManager.GetString("VersionNumberText", resourceCulture);
            }
        }
    }
}
